In [11]:
import scipy.io as sio
import numpy as np
dzip = sio.loadmat('dzip.mat')['dzip'][0]
azip = sio.loadmat('azip.mat')['azip']

In [12]:
len (dzip)

1707

In [13]:
len (azip[0])

1707

In [14]:
counter =0
for i in dzip:
    if i == 0:
        counter +=1
print(counter)

319


In [16]:
M0 = np.zeros(shape=(256,319))

In [17]:
M0.shape

(256, 319)

In [86]:
counter =0
for index , item  in enumerate(dzip):
    if item == 0:
        M0[:,counter] = azip[:,index]
        counter += 1
        
M0[:,318]    

array([-1.   , -1.   , -1.   , -0.567, -0.064,  0.979, -0.009, -0.167,
       -0.999, -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
       -1.   , -1.   , -1.   ,  0.405,  1.   ,  1.   ,  1.   ,  1.   ,
        0.482, -0.701, -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
       -1.   , -1.   , -1.   , -0.242,  1.   ,  1.   ,  1.   ,  1.   ,
        1.   ,  0.809,  0.351, -0.764, -1.   , -1.   , -1.   , -1.   ,
       -1.   , -1.   , -1.   , -0.091,  1.   ,  1.   ,  1.   ,  1.   ,
        0.848,  1.   ,  1.   ,  0.748, -0.536, -1.   , -1.   , -1.   ,
       -1.   , -0.987, -0.71 ,  0.861,  1.   ,  1.   ,  1.   ,  1.   ,
       -0.105,  0.963,  1.   ,  1.   ,  0.625, -0.662, -1.   , -1.   ,
       -1.   , -0.476,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
       -0.282, -0.457,  1.   ,  1.   ,  1.   ,  0.481, -0.768, -1.   ,
       -1.   , -0.249,  1.   ,  1.   ,  1.   ,  0.859, -0.046, -0.862,
       -0.962, -0.991, -0.255,  1.   ,  1.   ,  1.   ,  0.046, -1.   ,
      

In [107]:
U0 , S ,VT = np.linalg.svd(M0)
k = 3
var = 53
smallU0 = U[:,0:k]
d =azip[:,var]
I = np.eye(256)
v =np.matmul ((I - np.matmul (smallU0 , smallU0.T)) , d)
resut= np.linalg.norm(v)  
print (resut)
print (dzip[var])
print(U0[:,2])

10.25727020263881
0
[ 3.98898653e-03  3.93747880e-03  4.29368147e-03  3.86999254e-03
  8.56248566e-03  1.03812827e-02 -1.01912006e-02 -3.06888830e-02
 -2.70207522e-02 -5.48713791e-03 -7.56610184e-04  2.12160451e-04
  4.42569358e-03  4.00671009e-03  3.98898653e-03  3.98898653e-03
  3.98898653e-03  4.28826794e-03  4.72702873e-03  1.17171161e-02
  1.77439207e-02  5.06190173e-03 -1.41184654e-02 -1.71698462e-02
 -1.94162868e-02 -1.51246680e-02 -4.74484596e-03 -5.33311387e-03
  2.62552388e-03  4.16433167e-03  4.08897692e-03  3.98898653e-03
  3.98898653e-03  2.48074131e-03  3.38434471e-03  1.74358853e-02
  2.31434208e-02  1.79313699e-02  2.56327210e-02  5.16272155e-02
  6.40864279e-02  5.58893757e-02  2.73803400e-02  1.28920106e-02
  3.84598903e-03 -4.89202476e-04  3.67924663e-03  4.12501481e-03
  3.98025127e-03 -7.45786487e-04  1.38388420e-02  3.76997102e-02
  3.96825597e-02  4.32941341e-02  9.28082897e-02  1.35648474e-01
  1.33383163e-01  1.16910208e-01  8.97427968e-02  5.36571341e-02
  2.1

In [95]:
A = np.matmul (smallU0 , smallU0.T)
A.shape
print(A[0:5,0:5])

[[0.00918939 0.00917096 0.00910001 0.00874913 0.00779948]
 [0.00917096 0.0091526  0.0090819  0.00873128 0.00778221]
 [0.00910001 0.0090819  0.00901277 0.00866178 0.00771492]
 [0.00874913 0.00873128 0.00866178 0.00833444 0.00744676]
 [0.00779948 0.00778221 0.00771492 0.00744676 0.00674142]]


In [96]:
print(d[0:10])

[-1.    -1.    -1.    -1.    -1.    -0.454  0.879 -0.745 -1.    -1.   ]


In [99]:
v = np.matmul ((I - np.matmul (smallU0 , smallU0.T)) , d)
print(v[0:10])

[-0.0633313  -0.06471476 -0.06562173 -0.11806505 -0.22755067  0.10167933
  0.95495151 -0.97712088 -1.18657696 -0.77916507]


In [101]:
v.shape
print(v[0:10])

[-0.0633313  -0.06471476 -0.06562173 -0.11806505 -0.22755067  0.10167933
  0.95495151 -0.97712088 -1.18657696 -0.77916507]


4

In [106]:
for index , item  in enumerate(dzip):
    if item == 0:
        print (index)

8
11
18
49
53
58
63
65
68
72
80
95
97
101
102
104
106
108
111
116
122
130
132
134
139
157
169
176
180
185
189
192
207
218
222
225
229
235
248
254
266
270
271
272
278
279
280
283
288
294
295
304
317
321
328
332
333
334
335
355
363
365
370
372
375
388
390
400
402
405
409
411
414
419
433
435
438
443
449
451
453
458
461
471
479
481
486
489
493
498
500
513
515
520
521
528
538
541
543
548
579
580
590
595
600
637
641
649
651
654
655
657
658
662
663
667
670
672
677
682
684
687
688
690
693
708
711
716
724
731
732
733
736
737
741
742
748
754
758
759
764
767
769
774
778
779
782
784
789
793
794
799
804
807
809
813
816
820
823
824
827
829
830
833
834
835
837
839
840
845
848
849
851
853
856
857
864
865
867
869
870
874
875
878
879
882
883
885
887
888
892
893
897
898
902
915
916
919
921
923
928
930
938
940
944
955
965
967
969
979
992
993
998
1002
1003
1006
1010
1016
1028
1031
1034
1037
1038
1043
1064
1065
1070
1079
1099
1124
1125
1126
1149
1150
1153
1154
1158
1159
1163
1165
1168
1169
1172
1177
1179
11

In [49]:
dzip[8]

0

In [ ]:
d = 